version: "3.9"

services:
    backend:
        build: .
        command: bash -c "python migrate.py && python run.py"
        environment:
            DATABASE_URL: ${DATABASE_URL?}
            DEBUG: 0
            SECRET_KEY: ${SECRET_KEY?}
            DEFAULT_ADMIN_LOGIN: ${DEFAULT_ADMIN_LOGIN?}
            DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD?}
            ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES?}
            ROOT_PATH: /api
    proxy:
        ports:
            - ${PROXY_PORT?}:80
