version: "3.9"

services:
    backend:
        build: backend
        command: bash -c "python migrate.py && python run.py"
        environment:
            DATABASE_URL: "postgresql+psycopg2://postgres:password@database:5432/anticafe_db"
            DEBUG: 1
            SECRET_KEY: "secret"
            DEFAULT_ADMIN_LOGIN: admin
            DEFAULT_ADMIN_PASSWORD: admin
            ACCESS_TOKEN_EXPIRE_MINUTES: 60
            ROOT_PATH: /api
        depends_on:
            - database
        ports:
            - 8002:8000
    database:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: anticafe_db
        ports:
            - 5437:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
    proxy:
        build: proxy
        ports:
            - 81:80
    frontend:
        build: frontend

volumes:
    pg_data: {}
